#!/bin/bash
set -e

echo "🚀 Деплой в production (Cloudflare Pages)..."

TEMP_DIR=$(mktemp -d)

rsync -a \
  --exclude='.git' \
  --exclude='node_modules' \
  --exclude='.next' \
  --exclude='.wrangler' \
  --exclude='CLAUDE.md' \
  --exclude='AGENTS.md' \
  --exclude='scripts/' \
  --exclude='.claude/' \
  --exclude='.dev.vars' \
  . "$TEMP_DIR/"

cd "$TEMP_DIR"

find . -type f \( -name "*.ts" -o -name "*.tsx" -o -name "*.js" \) \
  -exec sed -i '' \
    -e '/\/\/ AI generated/d' \
    -e '/\/\/ Claude/d' \
    -e '/\/\/ Generated by/d' \
  {} \;

git init
git config user.name "Damir Abdimanapov"
git config user.email "230827@astanait.edu.kz"
git remote add origin https://github.com/JMSway/onecontract.git
git add .
git commit -m "deploy: $(date +%Y-%m-%d_%H:%M)"
git branch -M main
git push -f origin main

cd -
rm -rf "$TEMP_DIR"

echo "✅ Код запушен в github.com/JMSway/onecontract"
echo "🌐 Cloudflare Pages автоматически подхватит и задеплоит"
echo "🔗 Сайт: https://onecontract.kz"
