#!/bin/bash
# Деплой в production: фильтрует AI-маркеры и пушит в чистый репо

set -e

echo "🚀 Начинаю деплой в production..."

# Создаём временную чистую копию
TEMP_DIR=$(mktemp -d)
echo "📁 Копирую проект..."

# Копируем только нужные файлы (без .git, node_modules, .next)
rsync -a \
  --exclude='.git' \
  --exclude='node_modules' \
  --exclude='.next' \
  --exclude='CLAUDE.md' \
  --exclude='AGENTS.md' \
  --exclude='scripts/deploy-production.sh' \
  --exclude='.claude' \
  . "$TEMP_DIR/"

cd "$TEMP_DIR"

echo "🧹 Очищаю AI-маркеры..."

# Убираем AI-комментарии из кода
find . -type f \( -name "*.ts" -o -name "*.tsx" -o -name "*.js" -o -name "*.jsx" \) \
  -exec sed -i '' \
    -e '/\/\/ AI generated/d' \
    -e '/\/\/ Claude/d' \
    -e '/\/\/ Generated by/d' \
    -e '/\/\/ This file was created by/d' \
    -e '/\/\/ Автоматически/d' \
  {} \;

# Инициализируем git с человеческим автором
git init
git config user.name "Damir Abdimanapov"
git config user.email "230827@astanait.edu.kz"

# Добавляем production remote
git remote add origin https://github.com/JMSway/onecontract.git

# Коммитим и пушим (force — перезаписываем каждый раз)
git add .
git commit -m "Update production $(date +%Y-%m-%d_%H:%M)"
git branch -M main
git push -f origin main

# Убираем временную папку
cd -
rm -rf "$TEMP_DIR"

echo "✅ Production обновлён: github.com/JMSway/onecontract"
echo "🌐 Vercel/Cloudflare подхватит автоматически"
